# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c8e39408cc1477fcdc1555b438820285b91b3451d500478a457e4b7a322b35563f1cd813710a169e7791ed1e93d3aed1465ff1f0aef19965508d296dd24413

test:
  secret_key_base: 943f392c9b7be215c76edb9341cac5b9bf313f85a0b3dcd7fc7add5610b06b6d2ddb0aef43936ba5de158a10fbd5fa130881c8a1dcf5e7256a229d57c9733c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
